SELECT USER
FROM DUAL;
--==>> TEAM4



--○ 사용자 등록시 생성번호 자동 삽입 트리거 생성
CREATE OR REPLACE TRIGGER TRG_INESRT_USER
    BEFORE
    INSERT ON USING_USER
    FOR EACH ROW
BEGIN
    INSERT INTO USER_LIST VALUES(:NEW.USER_NUM);
END;