SELECT USER
FROM DUAL;
--==>> YAMEOKJA


--○ 사용자 등록시 생성번호 자동 삽입 트리거 생성
CREATE OR REPLACE TRIGGER TRG_INESRT_USER
    BEFORE
    INSERT ON USING_USER
    FOR EACH ROW
BEGIN
    INSERT INTO USER_LIST VALUES(:NEW.USER_NUM);
END;



--○ 가게가 검색어 삭제 또는 변경시 원래 입력했던 가게 검색어 찾아서 마이너스 1
CREATE OR REPLACE TRIGGER TRG_MINUS_STSKEY
    BEFORE
    DELETE ON ST_SEARCH_KEY
    FOR EACH ROW
BEGIN
    UPDATE SEARCH_KEY
    SET COUNT = COUNT - 1
    WHERE ST_NUM = :OLD.ST_NUM;
END;
--==>> Trigger TRG_MINUS_STSKEY이(가) 컴파일되었습니다.


-- 포인트 적립 시 포인트 로그 테이블에 자동 입력
CREATE OR REPLACE TRIGGER TRG_INSERT_POINT
    AFTER
    INSERT ON RV_BOX
    FOR EACH ROW
BEGIN
    INSERT INTO POINT_HISTORY(POINT_HIS_NUM, USER_NUM, ADD_DATE, POINT_LABEL_NUM)
    VALUES(POINTSEQ.NEXTVAL, :NEW.USER_NUM, SYSDATE, 1);
END;
--==>> Trigger TRG_INSERT_POINT이(가) 컴파일되었습니다.



CREATE OR REPLACE TRIGGER TRG_ST_LIST
    AFTER
    INSERT ON IN_PROCESS_NUM
    FOR EACH ROW
BEGIN
    DECLARE in_process_num NUMBER;
    
    -- 삽입된 행의 IN_PROCESS_NUM 값을 가져오기
    in_process_num := :NEW.IN_PROCESS_NUM;
    
    CASE WHEN 
